# Archivo: .github/workflows/publish.yml
name: Publish to PyPI

# Dispara el workflow al hacer push de un tag que empiece con 'v'
on:
  push:
    tags:
      - 'v*'
      # Ejemplo: v0.1.0, v1.2.3, etc.

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    
    # Aquí enlazas con el "Environment" que configuraste en PyPI, p.ej. "pypi"
    environment: pypi

    # Permisos OIDC obligatorios
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install build
        run: pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          publish: true
